name: CI

on:
  push:
    branches:
    - master
    - 'v*'
    tags:
    - '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - name: Security audit
          linux: bandit

        - name: PEP 8
          linux: codestyle

        - name: Python 3.9
          macos: py39-test-xdist
          posargs: -v

        - name: Python 3.9 (numpy 1.20)
          linux: py39-test-xdist-numpy120
          posargs: -v

        - name: Python 3.9 (numpy 1.21)
          macos: py39-test-xdist-numpy121
          posargs: -v

        - name: Python 3.10
          linux: py310-test-xdist
          posargs: -v

        - name: Python 3.11 (Windows)
          windows: py311-test-xdist
          posargs: -v

        - name: Python 3.11 (OSX)
          macos: py311-test-xdist
          posargs: -v

        - name: Python 3.11 with coverage
          linux: py311-test-cov
          posargs: -v
          coverage: codecov

        - name: Python 3.12 (Windows)
          windows: py312-test-xdist
          posargs: -v

        - name: Python 3.12 (OSX)
          macos: py312-test-xdist
          posargs: -v

        - name: Python 3.12 with coverage
          linux: py312-test-cov
          posargs: -v
          coverage: codecov

        - name: Python 3.12 (Windows with dev dependencies)
          windows: py312-test-xdist-devdeps
          posargs: -v

        - name: Python 3.12 (OSX with dev dependencies)
          macos: py312-test-xdist-devdeps
          posargs: -v

        - name: Python 3.12 (Linux with dev dependencies)
          linux: py312-test-xdist-devdeps
          posargs: -v
          pytest-results-summary: true
